services:
  foxogram-frontend:
    build:
      context: .
    restart: always
    networks:
      - traefik
    labels:
      traefik.enable: true
      traefik.http.routers.foxogram-frontend.rule: Host(`app.foxogram.su`)
      traefik.http.routers.foxogram-frontend.tls.certresolver: letsencrypt
      traefik.http.services.foxogram-frontend.loadbalancer.server.port: 80

networks:
  traefik:
    external: true
