services:
  foxogram-frontend:
    container_name: foxogram-frontend
    build:
      context: .
      args:
        NODE_ENV: production
    restart: always
    networks:
      - traefik
    labels:
      traefik.enable: true
      traefik.http.routers.foxogram-frontend.rule: Host(`app.foxogram.su`)
      traefik.http.routers.foxogram-frontend.tls.certresolver: letsencrypt
      traefik.http.services.foxogram-frontend.loadbalancer.server.port: 80

  foxogram-frontend-dev:
    container_name: foxogram-frontend-dev
    build:
      context: .
      args:
        NODE_ENV: development
    restart: always
    networks:
      - traefik
    labels:
      traefik.enable: true
      traefik.http.routers.foxogram-frontend-dev.rule: Host(`app.dev.foxogram.su`)
      traefik.http.routers.foxogram-frontend-dev.tls.certresolver: letsencrypt
      traefik.http.services.foxogram-frontend-dev.loadbalancer.server.port: 80

networks:
  traefik:
    external: true
