name: Deploy Frontend

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: cloud
    environment: ${{ github.ref_name == 'main' && 'production' || github.ref_name == 'dev' && 'development' || 'development' }}
    steps:
      - uses: actions/checkout@v4

      - name: Run Foxogram frontend
        run: docker compose up foxogram-frontend${{ github.ref_name == 'main' && '' || github.ref_name == 'dev' && '-dev' || '-dev' }} -d --build
